### ISSUE TITLE
jx-scm pull-request create to support ssh auth

### ISSUE THREAD

**Issue by jigsheth57** [jenkins-x-plugins/jx-scm#26]
Is there any plan in supporting ssh auth with github instead of username & token?

**Comment by garethjevans** [comment]
Hi @jigsheth57, I'd assume not. Most of the underlying APIs only accept token based auth.

Is there are particular scm provider that you'd like to use with ssh auth?

**Comment by garethjevans** [comment]
Ah, I see you said github - AFAIK github only supports token authentication - https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api
